/**
 * AMIRTHA AI — font embedder
 *
 * Subsets each WOFF2 in tools/fonts/ down to printable ASCII and writes the
 * base64 payloads to tools/fonts.generated.mjs.
 *
 *   node tools/build-fonts.mjs
 *
 * Run this only when the font files change; the generated module is committed
 * so neither the SVG build nor CI needs Python.
 *
 * Why subset: an SVG loaded through an <img> tag cannot fetch external
 * resources, so every face has to be inlined as a data: URI in each asset that
 * uses it. Full latin faces cost ~90 KB base64 per asset; ASCII-only costs
 * ~10 KB. All profile copy is ASCII by design — box drawing, blocks, bullets
 * and arrows are drawn as SVG shapes (see theme.mjs), never as glyphs, so they
 * can't fall back to a different font and break the layout grid.
 *
 * Requires: python -m pip install fonttools brotli
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

const run = promisify(execFile);
const TOOLS = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = join(TOOLS, 'fonts');

/** Printable ASCII. Everything the profile renders as text lives in here. */
const UNICODES = 'U+0020-007E';

/**
 * file stem -> export name in fonts.generated.mjs
 *
 * `advances: true` also emits a per-character advance table for that face.
 * The mono faces don't need one (every glyph is 0.6em), but the display face
 * is proportional, so without a table there is no way to check that a long
 * system name actually fits its card.
 */
const EXPORT_NAMES = {
  'space-grotesk-500': { name: 'displayMedium' },
  'space-grotesk-700': { name: 'displayBold', advances: true },
  'jetbrains-mono-400': { name: 'monoRegular' },
  'jetbrains-mono-500': { name: 'monoMedium' },
};

/** Advance width of every printable ASCII glyph, as a fraction of the em. */
async function advanceTable(fontPath) {
  const { stdout } = await run('python', ['-c', `
from fontTools.ttLib import TTFont
import json, sys
f = TTFont(sys.argv[1])
upm = f['head'].unitsPerEm
cmap = f.getBestCmap()
hmtx = f['hmtx']
out = {}
for cp, name in cmap.items():
    if 32 <= cp <= 126:
        out[chr(cp)] = round(hmtx[name][0] / upm, 5)
print(json.dumps(out, sort_keys=True))
`, fontPath]);
  return JSON.parse(stdout);
}

async function subset(srcPath) {
  const outPath = join(tmpdir(), `amirtha-subset-${Date.now()}-${Math.random().toString(36).slice(2)}.woff2`);
  await run('python', [
    '-m', 'fontTools.subset', srcPath,
    `--unicodes=${UNICODES}`,
    '--flavor=woff2',
    '--layout-features=', // no OpenType features needed; drops sizeable tables
    '--no-hinting',
    '--desubroutinize',
    `--output-file=${outPath}`,
  ]);
  return outPath;
}

const files = (await readdir(FONT_DIR)).filter((f) => f.endsWith('.woff2')).sort();
const entries = [];

for (const file of files) {
  const stem = file.replace(/\.woff2$/, '');
  const spec = EXPORT_NAMES[stem];
  if (!spec) throw new Error(`no export name mapped for ${file}`);
  const exportName = spec.name;

  const srcBytes = (await readFile(join(FONT_DIR, file))).length;
  const outPath = await subset(join(FONT_DIR, file));
  const subBytes = await readFile(outPath);
  const b64 = subBytes.toString('base64');

  const advances = spec.advances ? await advanceTable(outPath) : null;

  entries.push({ exportName, stem, b64, advances });
  console.log(
    `  ${stem.padEnd(20)} ${(srcBytes / 1024).toFixed(1).padStart(6)} KB` +
    ` -> ${(subBytes.length / 1024).toFixed(1).padStart(5)} KB woff2` +
    ` -> ${(b64.length / 1024).toFixed(1).padStart(5)} KB base64`
  );
}

const advanceExports = entries
  .filter((e) => e.advances)
  .map(
    (e) =>
      `/** ${e.stem}: advance width per ASCII glyph, in em. Build-time only —\n` +
      `  * this table is never written into an SVG. */\n` +
      `export const ${e.exportName}Advances = ${JSON.stringify(e.advances)};`
  );

const module = `// GENERATED by tools/build-fonts.mjs — do not edit by hand.
// Printable-ASCII (${UNICODES}) WOFF2 subsets, base64 encoded for inlining as
// data: URIs inside SVG <style> blocks. See build-fonts.mjs for the rationale.

${entries.map((e) => `/** ${e.stem} */\nexport const ${e.exportName} =\n  '${e.b64}';`).join('\n\n')}

${advanceExports.join('\n\n')}
`;

await writeFile(join(TOOLS, 'fonts.generated.mjs'), module);
console.log(`\n  wrote tools/fonts.generated.mjs (${(module.length / 1024).toFixed(1)} KB)`);
